version: 1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2015

environment:
  matrix:
    - platform: win32
      ADDR_MODEL: 32
      ARCH: win32-msvc14
      MSVCVERSION: 14.0
      PYTHONPATH: c:\Python36\
      PY_VER: 36
      BOOST_CFG: >-
          using python : 3.6 : c:/python36/python.exe : c:/python36/include : c:/python36/libs ;
    - platform: x64
      ADDR_MODEL: 64
      ARCH: x64-msvc14
      MSVCVERSION: 14.0
      PYTHONPATH: c:\Python36-x64\
      PY_VER: 36
      BOOST_CFG: >-
          using python : 3.6 : c:/python36-x64/python.exe : c:/python36-x64/include : c:/python36-x64/libs ;

    - platform: win32
      ADDR_MODEL: 32
      ARCH: win32-msvc14
      MSVCVERSION: 14.0
      PYTHONPATH: c:\Python37\
      PY_VER: 37
      BOOST_CFG: >-
          using python : 3.7 : c:/python37/python.exe : c:/python37/include : c:/python37/libs ;
    - platform: x64
      ADDR_MODEL: 64
      ARCH: x64-msvc14
      MSVCVERSION: 14.0
      PYTHONPATH: c:\Python37-x64\
      PY_VER: 37
      BOOST_CFG: >-
          using python : 3.7 : c:/python37-x64/python.exe : c:/python37-x64/include : c:/python37-x64/libs ;

    - platform: win32
      ADDR_MODEL: 32
      ARCH: win32-msvc14
      MSVCVERSION: 14.0
      PYTHONPATH: c:\Python38\
      PY_VER: 38
      BOOST_CFG: >-
          using python : 3.8 : c:/python38/python.exe : c:/python38/include : c:/python38/libs ;
    - platform: x64
      ADDR_MODEL: 64
      ARCH: x64-msvc14
      MSVCVERSION: 14.0
      PYTHONPATH: c:\Python38-x64\
      PY_VER: 38
      BOOST_CFG: >-
          using python : 3.8 : c:/python38-x64/python.exe : c:/python38-x64/include : c:/python38-x64/libs ;

init:
  - cmd: echo "List all projects and Python versions"
  - cmd: dir "C:\projects\"
  - cmd: dir "C:\"
  #RDP from start
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Boost
  - cmd: cd "C:\projects\"
  - cmd: md boost_build
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.zip
  - cmd: 7z -y x boost_1_73_0.zip -oC:\projects\boost_build\

  # adding a boost-config.jam file
  - cmd: echo %BOOST_CFG% >> %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cmd: type %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cmd: cd "C:\projects\boost-ci"

install:
  # Setting Visual Compiler
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  # building bootstrap
  - cmd: cd C:/projects/boost_build/boost_1_73_0
  - cmd: C:/projects/boost_build/boost_1_73_0/bootstrap.bat

clone_folder: C:\projects\boost-ci

build:
  parallel: true
  verbosity: minimal

build_script:
  - cmd: cd C:/projects/boost_build/boost_1_73_0
  # static libraries
  - cmd: b2 -j4 --with-python variant=release toolset=msvc-%MSVCVERSION% address-model=%ADDR_MODEL% threading=multi link=static runtime-link=static install
  # shared libraries
  - cmd: b2 -j4 --with-python variant=release toolset=msvc-%MSVCVERSION% address-model=%ADDR_MODEL% threading=multi link=shared runtime-link=shared install


after_build:
  - cmd: cd C:/boost
  - cmd: dir
  - 7z a boost-python-1.73.0_%ARCH%_py%PY_VER%.zip C:/boost
  - move boost-python-1.73.0_%ARCH%_py%PY_VER%.zip c:/projects/boost-ci/


on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: ./*.zip
